[versions]
#compose-bom = "2024.05.00"
compose-bom-dev = "2024.08.00-alpha01"
accompanist = "0.34.0"

[libraries]

#bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "compose-bom-dev" }
foundation = { module = "androidx.compose.foundation:foundation" }
animation = { module = "androidx.compose.animation:animation" }
runtime-android = { module = "androidx.compose.runtime:runtime-android" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-util = { module = "androidx.compose.ui:ui-util" }

material3-core = { module = "androidx.compose.material3:material3" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material-icons = { module = "androidx.compose.material:material-icons-extended" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-themeadapter = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-flowlayout = { module = 'com.google.accompanist:accompanist-flowlayout', version.ref = "accompanist" }
accompanist-navigation = { module = 'com.google.accompanist:accompanist-navigation-animation', version.ref = "accompanist" }

[bundles]
accompanist = ["accompanist-webview", "accompanist-permissions", "accompanist-themeadapter", "accompanist-systemuicontroller", "accompanist-flowlayout", "accompanist-navigation"]
material = ["material-icons", "material3-core", "material-icons-core"]
baselibs = ["foundation", "ui", "ui-tooling", "ui-util"]